version: '3.1'

services:
  postgres:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
